version: '3'
services:
  master:
    image: "grubykarol/locust"
    hostname: master
    ports:
     - "8089:8089"
     - "5557:5557"
     - "5558:5558"
    environment:
      ATTACKED_HOST: https://computer-database.gatling.io
      LOCUST_MODE: master
      LOCUST_MASTER_BIND_PORT: 5557
      TASK_DELAY_FROM: 5
      TASK_DELAY_TO: 30
      QUIET_MODE: "${QUIET_MODE:-false}"
    volumes:
      - .:/locust

  worker:
    image: "grubykarol/locust"
    environment:
      ATTACKED_HOST: https://computer-database.gatling.io
      LOCUST_MODE: worker
      LOCUST_MASTER_HOST: master
      LOCUST_MASTER_BIND_PORT: 5557
      NO_PROXY: master
      TASK_DELAY_FROM: 5
      TASK_DELAY_TO: 30
      QUIET_MODE: "${QUIET_MODE:-false}"
    volumes:
      - .:/locust
