apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: master
  template:
    metadata:
      labels:
        component: master
    spec:
      containers:
        - name: master
          image: grubykarol/locust
          ports:
            - containerPort: 5557
              name: comm
            - containerPort: 8089
              name: web-ui
          env:
            - name: ATTACKED_HOST
              valueFrom:
                configMapKeyRef:
                  name: locust-cm
                  key: ATTACKED_HOST
            - name: LOCUST_MODE
              value: MASTER
          volumeMounts:
            - mountPath: /locust
              name: locust-scripts
      volumes:
        - name: locust-scripts
          configMap:
            name: scripts-cm
          