apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  locustfile.py: |
    from locust import HttpUser, task, between

    class MyUser(HttpUser):
        @task
        def home(self):
            self.client.get("/")
    
        wait_time = between(5, 15)
